### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by aweimann** [PROBIC/mSWEEP#1]
Hi there,

When I try building mSWEEP I get the following error. Is there any way to fix that?

[ 11%] Building CXX object CMakeFiles/mSWEEP.dir/src/Sample.cpp.o
cc1plus: error: unrecognised command line option ‘-std=c++11’
make[2]: *** [CMakeFiles/mSWEEP.dir/src/Sample.cpp.o] Error 1
make[1]: *** [CMakeFiles/mSWEEP.dir/all] Error 2
make: *** [all] Error 2

Thanks, Aaron

**Comment by tmaklin** [comment]
Hi Aaron,

Building mSWEEP from source requires a compiler that supports C++11. What system and compiler are you using?

**Comment by aweimann** [comment]
Thanks! The gcc version on the cluster running on Ubuntu 12.04 is quite old: 4.3., which I suppose doesn't support C++11. I will either run it locally or get in touch with the IT support.

**Comment by aweimann** [comment]
I discovered a more recent version of the gcc compiler on our cluster, which solved the problem. Cheers!
