### ISSUE TITLE
Feature request: report the fraction of unassigned reads

### ISSUE THREAD

**Issue by jnalanko** [PROBIC/mSWEEP#21]
Hi, thanks for making this great tool!

It would be nice to know the fraction of the sample that could not be assigned to any target sequence. This would give an idea for how much of the sample is noise or outside of the pseudoalignment reference database. I know I can already get an idea of this number by parsing the pseudoalignment file myself, but it would be convenient if mSWEEP reported this in the comment section of the output file.

**Comment by tmaklin** [comment]
Added in a7bf816. Note: this is a breaking change to the output format and will incorporated in v2.0.0 release currently in development.
