### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by harry-thorpe** [PROBIC/mSWEEP#3]
Hi,

mSWEEP looks exciting, but I am having trouble installing it. I have pasted part of the stdout below:

ubuntu@harry:~/programs/mSWEEP$ mkdir build
ubuntu@harry:~/programs/mSWEEP$ cd build/
ubuntu@harry:~/programs/mSWEEP/build$ cmake ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/programs/mSWEEP/build
ubuntu@harry:~/programs/mSWEEP/build$ make
Scanning dependencies of target mSWEEP
[ 10%] Building CXX object CMakeFiles/mSWEEP.dir/src/read_bitfield.cpp.o
[ 20%] Building CXX object CMakeFiles/mSWEEP.dir/src/likelihood.cpp.o
/home/ubuntu/programs/mSWEEP/src/likelihood.cpp: In function ‘double lbeta(double, double)’:
/home/ubuntu/programs/mSWEEP/src/likelihood.cpp:7:10: error: ‘lgamma’ is not a member of ‘std’
   return(std::lgamma(x) + std::lgamma(y) - std::lgamma(x + y));
          ^

There are more similar errors after this which I haven't shown here. It looks like there is a problem with the lgamma function, is this due to a library I am missing or something?

Thanks,

Harry

**Comment by tmaklin** [comment]
Hi Harry,

This looks like a problem with the includes. I can't reproduce it but have a pretty good guess of what's causing it. I've added a commit that should hopefully fix the problem but please let me know if it doesn't so we can work it out.

Tommi

**Comment by harry-thorpe** [comment]
Hi Tommi,

Perfect, it has built now!

Thanks!

Harry
